# Here, we ganna implement numpy

In [1]:
import numpy as np

In [6]:
array1d = np.array([2, 3, 4, 6, 7]) #python list coverted into numpy array
array2d = np.array([[2, 3], [7, 0]])

In [8]:
new_array= np.asarray(array1d)
new_array

array([2, 3, 4, 6, 7])

In [12]:
type(array1d)

numpy.ndarray

In [13]:
array1d_new_type = array1d.astype(np.float32)

In [14]:
array1d_new_type

array([2., 3., 4., 6., 7.], dtype=float32)

In [15]:
print(array1d_new_type.shape)
print(array2d.shape)

(5,)
(2, 2)


In [16]:
print(array1d_new_type.ndim)
print(array2d.ndim)

1
2


In [18]:
array_identity = np.identity(4)
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])